In [1]:
!pip install pandas

Requirement already satisfied: pandas in C:\Users\kohen\.anaconda\New folder\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\kohen\.anaconda\New folder\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\kohen\.anaconda\New folder\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\kohen\.anaconda\New folder\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\kohen\.anaconda\New folder\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
!pip install numpy

Requirement already satisfied: numpy in C:\Users\kohen\.anaconda\New folder\Lib\site-packages (2.4.6)

In [3]:
!pip install matplotlib seaborn

Requirement already satisfied: matplotlib in C:\Users\kohen\.anaconda\New folder\Lib\site-packages (3.11.0)
Requirement already satisfied: seaborn in C:\Users\kohen\.anaconda\New folder\Lib\site-packages (0.13.2)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\kohen\.anaconda\New folder\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\kohen\.anaconda\New folder\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\kohen\.anaconda\New folder\Lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\kohen\.anaconda\New folder\Lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.25 in C:\Users\kohen\.anaconda\New folder\Lib\site-packages (from matplotlib) (2.4.6)
Requirement already satisfied: packaging>=20.0 in C:\Users\kohen\.anaconda\New folder\Lib\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=9 in C:\Users\kohen\.anaconda\New folder\Lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\kohen\.anaconda\New folder\Lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\kohen\.anaconda\New folder\Lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pandas>=1.2 in C:\Users\kohen\.anaconda\New folder\Lib\site-packages (from seaborn) (3.0.3)
Requirement already satisfied: tzdata in C:\Users\kohen\.anaconda\New folder\Lib\site-packages (from pandas>=1.2->seaborn) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\kohen\.anaconda\New folder\Lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

In [4]:
import sqlite3

In [5]:
import pandas as pd

conn = sqlite3.connect('my_data.db')

cursor = conn.cursor()

In [10]:

pd.read_csv('sales.csv').to_sql('sales',conn, if_exists='replace',index=False)

20

# * Task 1: retrieve sale_date, product and price from sales tables *

In [11]:
pd.read_sql_query('''
SELECT sale_date, product, price FROM sales
''', conn)

    sale_date     product   price
0    9/1/2026      Laptop  999.99
1    9/1/2026       Mouse   24.99
2    9/2/2026     Monitor  199.99
3    9/2/2026    Keyboard   49.99
4    9/3/2026      Laptop  999.99
5    9/3/2026  Headphones   79.99
6    9/4/2026       Mouse   24.99
7    9/4/2026     Monitor  199.99
8    9/5/2026      Laptop  999.99
9    9/5/2026    Keyboard   49.99
10   9/6/2026  Headphones   79.99
11   9/6/2026      Tablet  449.99
12   9/7/2026       Mouse   24.99
13   9/7/2026      Tablet  449.99
14   9/8/2026     Monitor  199.99
15   9/8/2026      Laptop  999.99
16   9/9/2026    Keyboard   49.99
17   9/9/2026  Headphones   79.99
18  9/10/2026      Tablet  449.99
19  9/10/2026       Mouse   24.99

In [18]:
pd.read_csv('hr_employees.csv').to_sql('employees',conn,if_exists = 'replace',index = False)

30

# * Task 2: Find employees in Chicago with more than 10 years of experience using WHERE and AND *

In [19]:
pd.read_sql_query('''
SELECT name, city, years_experience
FROM employees
WHERE years_experience > 10 AND city = 'Chicago' 
''', conn)

   name     city  years_experience
0  Lily  Chicago                17

# * Task 3: Display the three largest properties by square footage using ORDER BY and LIMIT *

In [21]:
pd.read_csv("realestate_listings.csv").to_sql('listings',conn, if_exists = 'replace',index = False)

25

In [22]:
pd.read_sql_query('''
SELECT property_type, sqft, bedrooms
FROM listings 
ORDER BY sqft DESC
LIMIT 3
''',conn)

  property_type  sqft  bedrooms
0         Condo  3736         5
1         Condo  3693         5
2         House  3499         1

# * Task 4: Calculate total weekly impressions using SUM() and GROUP BY

In [23]:
pd.read_csv("marketing_campaigns.csv").to_sql('campaigns', conn, if_exists = "replace",index = False)

40

In [24]:
pd.read_sql_query('''
SELECT week, 
        SUM(impressions) AS total_weekly_impressions
FROM campaigns
GROUP BY week
ORDER BY week ASC
''',conn)

   week  total_weekly_impressions
0     1                    181454
1     2                     74972
2     3                    193242
3     4                    180795
4     5                    264615
5     6                    229892
6     7                    235470
7     8                    253354

# * Task 5: Find dates when total restaurant sales exceeded $400 *

In [25]:
pd.read_csv("restaurant_orders.csv").to_sql('orders', conn, if_exists = 'replace', index = False)

50

In [26]:
pd.read_sql_query('''
SELECT order_date, SUM(order_total) AS total_sales
FROM orders 
GROUP BY order_date 
HAVING SUM(order_total) > 400 
ORDER BY order_date
''', conn)

   order_date  total_sales
0  2026-10-02       492.14
1  2026-10-05       850.10
2  2026-10-07       415.94
3  2026-10-12       633.98

# * Task 6: Find the average patient age and longest waiting time for each doctor *

In [27]:
pd.read_csv("clinic_visits.csv").to_sql('visits', conn, if_exists = 'replace', index = False)

35

In [28]:
pd.read_sql_query('''
SELECT doctor,
        AVG(patient_age) AS avg_patient_age,
        MAX(wait_minutes) AS longest_waiting_mintues
FROM visits
GROUP BY doctor
ORDER BY  wait_minutes DESC
''', conn)

      doctor  avg_patient_age  longest_waiting_mintues
0  Dr. Gomez        33.666667                       75
1  Dr. Adams        47.000000                       75
2  Dr. Scott        44.857143                       63
3  Dr. Patel        45.375000                       59
4   Dr. Chen        57.600000                       50

# * Task 7: Join Customer and Transaction Tables to Calculate Total Transaction Amount by Branch *

In [29]:
pd.read_csv("bank_customers.csv").to_sql("customers", conn, if_exists = 'replace', index = False)
pd.read_csv("bank_transactions.csv").to_sql("transactions", conn, if_exists = 'replace', index = False)

45

In [30]:
pd.read_sql_query('''
SELECT c.branch, 
        SUM(t.amount) AS total_transaction_amount
FROM "customers" c
JOIN "transactions" t
        ON c.customer_id = t.customer_id
GROUP BY c.branch
ORDER BY total_transaction_amount DESC
''', conn)

      branch  total_transaction_amount
0  Northgate                  19546.49
1    Airport                  15177.98
2   Westside                  13996.30
3    Main St                   3581.19